### ISSUE TITLE
web

### ISSUE THREAD

**Issue by MMAKENPO** [mishokU/ItunesMusic#1]
HELLO MY FRIEND!!!TELL ME PLEASE WE CAN SEARCH SONGS AND ALBUMS FROM ITUNES?AND IF YES,PLEASE COULD YOU TELL ME THE WEB?

**Comment by MMAKENPO** [comment]
please bro there is any web?

**Comment by mishokU** [comment]
Hey man ! I think there is no web to get that possible information, but you can google to this problem, especially on this web site.

**Comment by MMAKENPO** [comment]
hey man thanks where answer me!!!no,I mean if there is any web for your itunes project

**Comment by mishokU** [comment]
Oh, sorry for misunderstanding, no i don't

**Comment by MMAKENPO** [comment]
my friend pleaseeeeeee I am begging you can you make a web version?I will preciate it so muchhhhhhhhhhhhhhhhhh

**Comment by mishokU** [comment]
What, no, sorry.

**Comment by MMAKENPO** [comment]
ok...thanks anyway!!!
